# Generated by Django 4.2 on 2025-01-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technologies_used', models.CharField(help_text='Comma-separated list of technologies (e.g., Django, React, PostgreSQL)', max_length=200)),
                ('live_demo_url', models.URLField(blank=True, null=True)),
                ('github_repo_url', models.URLField(blank=True, null=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='projects/images/')),
            ],
        ),
    ]
