# Generated by Django 4.2 on 2025-02-15 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='brief_about_the_project',
            field=models.TextField(default='', help_text='A brief description of the project, this will be displayed on the project section of the website', max_length=1000),
        ),
        migrations.AddField(
            model_name='project',
            name='one_line_about_the_project',
            field=models.CharField(default='', help_text='A one-line description of the project, this will be displayed on the project card', max_length=200),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
        ),
    ]
