# Generated by Django 4.2 on 2025-02-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='preview_image',
            new_name='Card_image',
        ),
    ]
