# Generated by Django 4.2 on 2025-02-17 18:02

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_preview_image_project_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='level',
            field=models.IntegerField(default=0, help_text='Comma-separated list of technologies (e.g., 100, 90, 70).Give the level based on the order of the technologies used. if you given django as on the first in the technologies used then give 100 as the level on first'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Card_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/', validators=[apps.projects.models.validate_square_image]),
        ),
        migrations.AlterField(
            model_name='project',
            name='brief_about_the_project',
            field=models.TextField(default='', help_text='A brief description of the project, this will be displayed on the project section of the website.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='one_line_about_the_project',
            field=models.CharField(default='', help_text='A one-line description of the project, this will be displayed on the project card.', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies_used',
            field=models.CharField(help_text='Comma-separated list of technologies (e.g., Django, React, PostgreSQL).', max_length=200),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='projects/images/', validators=[apps.projects.models.validate_landscape_image]),
        ),
    ]
