# Generated by Django 4.2 on 2025-02-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_level_alter_project_card_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='level',
            field=models.CharField(help_text='Comma-separated list of technologies (e.g., 100, 90, 70).Give the level based on the order of the technologies used. if you given django as on the first in the technologies used then give 100 as the level on first', max_length=200),
        ),
    ]
