# Generated by Django 4.2 on 2025-02-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='level',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies_used',
        ),
        migrations.AddField(
            model_name='project',
            name='level_in_1',
            field=models.IntegerField(default=0, help_text='Give the first technology used level'),
        ),
        migrations.AddField(
            model_name='project',
            name='level_in_2',
            field=models.IntegerField(default=0, help_text='Give the second technology used level'),
        ),
        migrations.AddField(
            model_name='project',
            name='level_in_3',
            field=models.IntegerField(default=0, help_text='Give the third technology used level'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_used_1',
            field=models.CharField(default='', help_text='Comma-separated list of technologies (e.g., Django, React, PostgreSQL).', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_used_2',
            field=models.CharField(default='', help_text='Comma-separated list of technologies (e.g., Django, React, PostgreSQL).', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_used_3',
            field=models.CharField(default='', help_text='Comma-separated list of technologies (e.g., Django, React, PostgreSQL).', max_length=200),
        ),
    ]
