# Generated by Django 4.2 on 2025-02-19 16:00

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='challenges_faced_with_the_project',
            field=models.TextField(default='', help_text='A brief description of the project, this will be displayed on the project section of the website.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='Card_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/', validators=[apps.projects.models.validate_landscape_image]),
        ),
    ]
