# Generated by Django 4.2 on 2025-02-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_challenges_faced_with_the_project_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
