# Generated by Django 4.2 on 2025-02-19 17:39

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_delete_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Project_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/', validators=[apps.projects.models.validate_landscape_image]),
        ),
        migrations.AddField(
            model_name='project',
            name='Project_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/', validators=[apps.projects.models.validate_landscape_image]),
        ),
        migrations.AddField(
            model_name='project',
            name='Project_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/', validators=[apps.projects.models.validate_landscape_image]),
        ),
        migrations.AddField(
            model_name='project',
            name='Project_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/', validators=[apps.projects.models.validate_landscape_image]),
        ),
        migrations.AddField(
            model_name='project',
            name='Project_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/', validators=[apps.projects.models.validate_landscape_image]),
        ),
    ]
