# Generated by Django 4.2 on 2025-02-28 16:44

import apps.projects.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_project_image_1_project_project_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Card_image',
            field=models.ImageField(null=True, upload_to='projects/images/', validators=[apps.projects.models.validate_landscape_image]),
        ),
        migrations.AlterField(
            model_name='project',
            name='Project_image_1',
            field=models.ImageField(null=True, upload_to='projects/images/', validators=[apps.projects.models.validate_landscape_image]),
        ),
        migrations.AlterField(
            model_name='project',
            name='Project_image_2',
            field=models.ImageField(null=True, upload_to='projects/images/', validators=[apps.projects.models.validate_landscape_image]),
        ),
        migrations.AlterField(
            model_name='project',
            name='Project_image_3',
            field=models.ImageField(null=True, upload_to='projects/images/', validators=[apps.projects.models.validate_landscape_image]),
        ),
        migrations.AlterField(
            model_name='project',
            name='Project_image_4',
            field=models.ImageField(null=True, upload_to='projects/images/', validators=[apps.projects.models.validate_landscape_image]),
        ),
        migrations.AlterField(
            model_name='project',
            name='Project_image_5',
            field=models.ImageField(null=True, upload_to='projects/images/', validators=[apps.projects.models.validate_landscape_image]),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
