# Generated by Django 4.2 on 2025-03-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_level_in_1_alter_project_level_in_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_domain',
        ),
    ]
