# Generated by Django 5.1.7 on 2025-03-16 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_project_project_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='level_in_1',
            field=models.IntegerField(default=0, help_text='Give the third technology used level (1-100)', validators=[django.core.validators.MinValueValidator(35), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='level_in_2',
            field=models.IntegerField(default=0, help_text='Give the third technology used level (1-100)', validators=[django.core.validators.MinValueValidator(35), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='level_in_3',
            field=models.IntegerField(default=0, help_text='Give the third technology used level (1-100)', validators=[django.core.validators.MinValueValidator(35), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
