# Generated by Django 5.1.7 on 2025-03-18 19:43

import apps.projects.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_project_level_in_1_alter_project_level_in_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Card_image',
            field=models.ImageField(help_text='this image will be displayed on the project card', null=True, upload_to='projects/images/', validators=[apps.projects.models.validate_landscape_image]),
        ),
        migrations.AlterField(
            model_name='project',
            name='brief_about_the_project',
            field=models.TextField(default='', help_text='A detailed description of the project for display in the project section of the website.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='challenges_faced_with_the_project',
            field=models.TextField(default='', help_text='Description of challenges encountered during the project development.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_repo_url',
            field=models.URLField(blank=True, help_text='URL for the GitHub repository of the project.If it is blank the button will be hidden.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='level_in_1',
            field=models.IntegerField(default=0, help_text='Proficiency level of the first technology used (35-100).', validators=[django.core.validators.MinValueValidator(35), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='level_in_2',
            field=models.IntegerField(default=0, help_text='Proficiency level of the second technology used (35-100).', validators=[django.core.validators.MinValueValidator(35), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='level_in_3',
            field=models.IntegerField(default=0, help_text='Proficiency level of the third technology used (35-100).', validators=[django.core.validators.MinValueValidator(35), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_demo_url',
            field=models.URLField(blank=True, help_text='URL for the live demo of the project.If it is blank the button will be hidden.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Enter the name of the project', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='one_line_about_the_project',
            field=models.CharField(default='', help_text='A concise one-line description of the project to be displayed on the project card.', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies_used_1',
            field=models.CharField(default='', help_text='Provied the name of the first technology used (e.g., Django, React, PostgreSQL).', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies_used_2',
            field=models.CharField(default='', help_text='Provided the name of the second technology used (e.g., Django, React, PostgreSQL).', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies_used_3',
            field=models.CharField(default='', help_text='Provided the name of the third technology used (e.g., Django, React, PostgreSQL).', max_length=200),
        ),
    ]
