# Generated by Django 5.1.7 on 2025-03-18 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_project_card_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ProjectMessage',
        ),
    ]
