# Generated by Django 5.1.7 on 2025-03-18 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_rename_contact_projectmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmessage',
            old_name='created_at',
            new_name='Recived_at',
        ),
    ]
