# Generated by Django 5.1.7 on 2025-03-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_rename_created_at_projectmessage_recived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmessage',
            name='Ai_response',
            field=models.TextField(null=True),
        ),
    ]
