# Generated by Django 5.1.7 on 2025-03-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_projectmessage_ai_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmessage',
            name='Ai_response',
            field=models.TextField(),
        ),
    ]
