# Generated by Django 5.1.7 on 2025-03-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_projectmessage_ai_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmessage',
            name='Reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
