# Generated by Django 5.1.7 on 2025-05-22 22:42

import apps.projects.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_projectmessage_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Card_image',
            field=models.ImageField(help_text='this image will be displayed on the project card', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='projects/images/', validators=[apps.projects.models.validate_landscape_image]),
        ),
        migrations.AlterField(
            model_name='project',
            name='Project_image_1',
            field=models.ImageField(null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='projects/images/', validators=[apps.projects.models.validate_landscape_image]),
        ),
        migrations.AlterField(
            model_name='project',
            name='Project_image_2',
            field=models.ImageField(null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='projects/images/', validators=[apps.projects.models.validate_landscape_image]),
        ),
        migrations.AlterField(
            model_name='project',
            name='Project_image_3',
            field=models.ImageField(null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='projects/images/', validators=[apps.projects.models.validate_landscape_image]),
        ),
        migrations.AlterField(
            model_name='project',
            name='Project_image_4',
            field=models.ImageField(null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='projects/images/', validators=[apps.projects.models.validate_landscape_image]),
        ),
        migrations.AlterField(
            model_name='project',
            name='Project_image_5',
            field=models.ImageField(null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='projects/images/', validators=[apps.projects.models.validate_landscape_image]),
        ),
    ]
