# Generated by Django 4.2 on 2025-03-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_service_icon_alter_service_others_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Othersicon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
