# Generated by Django 4.2 on 2025-03-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_othersicon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Othersicon',
            new_name='Othericon',
        ),
    ]
