# Generated by Django 5.1.7 on 2025-03-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_othersicon_service_othericon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Other_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
