# Generated by Django 4.2 on 2025-01-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('social_media_links', models.JSONField(help_text="Add links as a JSON object (e.g., {'LinkedIn': 'url', 'GitHub': 'url'})")),
            ],
        ),
    ]
