# Generated by Django 4.2 on 2025-01-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contactinfo_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='discord_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='facebook_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='github_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='instagram_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='linkedin_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='reddit_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='threads_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='twitter_active',
            field=models.BooleanField(default=True),
        ),
    ]
