# Generated by Django 4.2 on 2025-01-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contactinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='discord',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='discord_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='facebook_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='github_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='instagram_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='linkedin_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='reddit_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='threads_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='twitter_active',
            field=models.BooleanField(default=False),
        ),
    ]
