# Generated by Django 4.2 on 2025-02-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contactinfo_phone_number_alter_contactinfo_discord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='ai_details',
            field=models.TextField(default='You are an AI assistant for a website contact form. Please generate a helpful and professional response to the following user inquiry:', help_text="Customize the system prompt for the AI assistant. Tell your assistant's name and describe details of you"),
        ),
    ]
