# Generated by Django 5.1.7 on 2025-03-16 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contacted',
        ),
    ]
