# Generated by Django 5.1.7 on 2025-03-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_remove_contact_contacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Ai_Response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='discord',
            field=models.CharField(blank=True, help_text='Enter your Discord profile URL.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='discord_active',
            field=models.BooleanField(default=False, help_text='Check if you want to show your Discord profile URL.'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter your preferred email address to receive customer inquiries.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='facebook',
            field=models.URLField(blank=True, help_text='Enter your Facebook profile URL.', null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='facebook_active',
            field=models.BooleanField(default=False, help_text='Check if you want to show your Facebook profile URL.'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='github',
            field=models.URLField(blank=True, help_text='Enter your GitHub profile URL.', null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='github_active',
            field=models.BooleanField(default=False, help_text='Check if you want to show your GitHub profile URL.'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='instagram',
            field=models.URLField(blank=True, help_text='Enter your Instagram profile URL.', null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='instagram_active',
            field=models.BooleanField(default=False, help_text='Check if you want to show your Instagram profile URL.'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Enter your LinkedIn profile URL.', null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='linkedin_active',
            field=models.BooleanField(default=False, help_text='Check if you want to show your LinkedIn profile URL.'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter your preferred phone number to receive customer inquiries.', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='reddit',
            field=models.URLField(blank=True, help_text='Enter your Reddit profile URL.', null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='reddit_active',
            field=models.BooleanField(default=False, help_text='Check if you want to show your Reddit profile URL.'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='threads',
            field=models.URLField(blank=True, help_text='Enter your Threads profile URL.', null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='threads_active',
            field=models.BooleanField(default=False, help_text='Check if you want to show your Threads profile URL.'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='twitter',
            field=models.URLField(blank=True, help_text='Enter your Twitter profile URL.', null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='twitter_active',
            field=models.BooleanField(default=False, help_text='Check if you want to show your Twitter profile URL.'),
        ),
    ]
