# Generated by Django 5.1.7 on 2025-03-18 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_contact_ai_response_alter_contactinfo_discord_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created_at',
            new_name='Recived_at',
        ),
    ]
