# Generated by Django 5.1.7 on 2025-03-18 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_rename_created_at_contact_recived_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Client_Message',
        ),
    ]
