# Generated by Django 5.1.7 on 2025-03-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_rename_contact_client_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_message',
            name='Reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
