# Generated by Django 5.1.7 on 2025-03-18 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_client_message_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_message',
            name='Reply',
        ),
    ]
