# Generated by Django 5.1.7 on 2025-03-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_remove_client_message_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_message',
            name='Reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
