# Generated by Django 4.2 on 2025-02-07 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Programming Language', 'Programming Language'), ('Framework', 'Framework'), ('Tools', 'Tools'), ('Soft Skills', 'Soft Skills'), ('Other', 'Other')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(default='skills/icons/default.png', upload_to='skills/icons/')),
                ('level', models.IntegerField(default=0)),
                ('skill_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skilltype')),
            ],
        ),
    ]
