# Generated by Django 4.2 on 2025-02-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_remove_skill_icon_alter_skill_skill_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(choices=[('Programming Language', 'Programming Language'), ('Framework', 'Framework'), ('Tools', 'Tools'), ('Soft Skills', 'Soft Skills')], max_length=100, unique=True),
        ),
    ]
