# Generated by Django 4.2 on 2025-02-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
