# Generated by Django 4.2 on 2025-02-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_alter_skill_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.CharField(default='Database', max_length=100, verbose_name='Database')),
                ('select_database', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL')], max_length=100)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.CharField(default='Framework', max_length=100, verbose_name='Framework')),
                ('select_framework', models.CharField(choices=[('django', 'Django'), ('flask', 'Flask')], max_length=100)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(default='Other', max_length=100)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Soft_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.CharField(default='Soft Skills', max_length=100, verbose_name='Soft Skills')),
                ('select_soft_skills', models.CharField(choices=[('communication', 'Communication'), ('teamwork', 'Teamwork')], max_length=100)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.CharField(default='Tools', max_length=100, verbose_name='Tools')),
                ('select_tools', models.CharField(choices=[('git', 'Git'), ('docker', 'Docker')], max_length=100)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_type',
        ),
        migrations.AddField(
            model_name='skill',
            name='selected',
            field=models.CharField(default='Programming Language', max_length=100, verbose_name='Programming Language'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('other', 'Other')], max_length=100),
        ),
    ]
