# Generated by Django 4.2 on 2025-02-09 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_database_framework_other_soft_skills_tools_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='ProgrammingLanguage',
        ),
    ]
