# Generated by Django 4.2 on 2025-02-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_rename_skill_programminglanguage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='selected',
        ),
        migrations.RemoveField(
            model_name='framework',
            name='selected',
        ),
        migrations.RemoveField(
            model_name='programminglanguage',
            name='selected',
        ),
        migrations.RemoveField(
            model_name='soft_skills',
            name='selected',
        ),
        migrations.RemoveField(
            model_name='tools',
            name='selected',
        ),
        migrations.AlterField(
            model_name='database',
            name='select_database',
            field=models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='framework',
            name='select_framework',
            field=models.CharField(choices=[('django', 'Django'), ('flask', 'Flask')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='name',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='soft_skills',
            name='select_soft_skills',
            field=models.CharField(choices=[('communication', 'Communication'), ('teamwork', 'Teamwork')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tools',
            name='select_tools',
            field=models.CharField(choices=[('git', 'Git'), ('docker', 'Docker')], max_length=100, null=True),
        ),
    ]
