# Generated by Django 4.2 on 2025-02-09 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_remove_database_selected_remove_framework_selected_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Soft_Skills',
            new_name='SoftSkills',
        ),
    ]
