# Generated by Django 4.2 on 2025-02-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0009_alter_database_select_database_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programminglanguage',
            name='name',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('c', 'C'), ('cpp', 'C++'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('csharp', 'C#'), ('swift', 'Swift'), ('kotlin', 'Kotlin'), ('go', 'Go'), ('rust', 'Rust'), ('dart', 'Dart'), ('ruby', 'Ruby'), ('php', 'PHP'), ('r', 'R'), ('julia', 'Julia'), ('sql', 'SQL'), ('plsql', 'PL/SQL'), ('tsql', 'T-SQL'), ('graphql', 'GraphQL'), ('perl', 'Perl'), ('lua', 'Lua'), ('haskell', 'Haskell'), ('clojure', 'Clojure'), ('scala', 'Scala'), ('erlang', 'Erlang'), ('elixir', 'Elixir'), ('fsharp', 'F#'), ('ocaml', 'OCaml'), ('prolog', 'Prolog'), ('lisp', 'Lisp'), ('scheme', 'Scheme'), ('fortran', 'Fortran'), ('cobol', 'COBOL'), ('basic', 'BASIC'), ('smalltalk', 'Smalltalk'), ('ada', 'Ada'), ('algol', 'ALGOL'), ('pascal', 'Pascal'), ('modula2', 'Modula-2'), ('vhdl', 'VHDL'), ('verilog', 'Verilog'), ('jcl', 'JCL'), ('xquery', 'XQuery'), ('postscript', 'PostScript'), ('bash', 'Bash'), ('powershell', 'PowerShell'), ('nim', 'Nim'), ('zig', 'Zig'), ('gams', 'GAMS'), ('idl', 'IDL'), ('latex', 'LaTeX'), ('brainfuck', 'Brainfuck'), ('whitespace', 'Whitespace'), ('intercal', 'INTERCAL'), ('malbolge', 'Malbolge'), ('piet', 'Piet'), ('befunge', 'Befunge'), ('qsharp', 'Q#'), ('qiskit', 'Qiskit'), ('quipper', 'Quipper'), ('silq', 'Silq'), ('cirq', 'Cirq')], max_length=100, null=True),
        ),
    ]
