# Generated by Django 4.2 on 2025-03-02 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0010_alter_programminglanguage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='level',
            field=models.IntegerField(default=0, help_text='Give the third technology used level (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='framework',
            name='level',
            field=models.IntegerField(default=0, help_text='Give the third technology used level (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='other',
            name='level',
            field=models.IntegerField(default=0, help_text='Give the third technology used level (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='level',
            field=models.IntegerField(default=0, help_text='Give the third technology used level (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='softskills',
            name='level',
            field=models.IntegerField(default=0, help_text='Give the third technology used level (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tools',
            name='level',
            field=models.IntegerField(default=0, help_text='Give the third technology used level (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
