# Generated by Django 4.2 on 2025-03-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0012_alter_softskills_select_soft_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softskills',
            name='select_soft_skills',
            field=models.CharField(choices=[('communication', 'Communication'), ('typewriting', 'Typewriting'), ('teamwork', 'Teamwork'), ('problem_solving', 'Problem Solving'), ('critical_thinking', 'Critical Thinking'), ('leadership', 'Leadership'), ('adaptability', 'Adaptability'), ('creativity', 'Creativity'), ('time_management', 'Time Management'), ('emotional_intelligence', 'Emotional Intelligence'), ('conflict_resolution', 'Conflict Resolution'), ('decision_making', 'Decision Making'), ('work_ethic', 'Work Ethic'), ('stress_management', 'Stress Management'), ('negotiation', 'Negotiation'), ('self_motivation', 'Self-Motivation'), ('attention_to_detail', 'Attention to Detail'), ('interpersonal_skills', 'Interpersonal Skills'), ('active_listening', 'Active Listening'), ('collaboration', 'Collaboration'), ('presentation_skills', 'Presentation Skills'), ('customer_service', 'Customer Service'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
