# Generated by Django 4.2 on 2025-03-15 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0014_skills_delete_database_delete_framework_delete_other_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='level',
            new_name='database_level',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='name',
            new_name='programming_language',
        ),
        migrations.AddField(
            model_name='skills',
            name='framework_level',
            field=models.IntegerField(default=0, help_text='Give the third technology used level (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='skills',
            name='language_level',
            field=models.IntegerField(default=0, help_text='Give the third technology used level (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='skills',
            name='soft_skills_level',
            field=models.IntegerField(default=0, help_text='Give the third technology used level (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='skills',
            name='tools_level',
            field=models.IntegerField(default=0, help_text='Give the third technology used level (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
