# Generated by Django 5.1.7 on 2025-05-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0022_alter_database_custom_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softskills',
            name='select_soft_skills',
            field=models.CharField(blank=True, choices=[('Communication', 'Communication'), ('Typewriting', 'Typewriting'), ('Teamwork', 'Teamwork'), ('Problem solving', 'Problem Solving'), ('Critical thinking', 'Critical Thinking'), ('Leadership', 'Leadership'), ('Adaptability', 'Adaptability'), ('Creativity', 'Creativity'), ('Time management', 'Time Management'), ('Emotional intelligence', 'Emotional Intelligence'), ('Conflict resolution', 'Conflict Resolution'), ('Decision making', 'Decision Making'), ('Work ethic', 'Work Ethic'), ('Stress management', 'Stress Management'), ('Negotiation', 'Negotiation'), ('Self motivation', 'Self-Motivation'), ('Attention to detail', 'Attention to Detail'), ('Interpersonal skills', 'Interpersonal Skills'), ('Active listening', 'Active Listening'), ('Collaboration', 'Collaboration'), ('Presentation_skills', 'Presentation Skills'), ('Customer service', 'Customer Service'), ('Other', 'Other')], help_text="Please select either 'select a soft skill from the list' or specify a custom entry.", max_length=100, null=True),
        ),
    ]
