# Generated by Django 5.1.7 on 2025-05-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0023_alter_softskills_select_soft_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework',
            name='select_framework',
            field=models.CharField(blank=True, choices=[('Django', 'Django'), ('Flask', 'Flask'), ('Fastapi', 'FastAPI'), ('Express', 'Express.js'), ('Nestjs', 'NestJS'), ('Spring', 'Spring Boot'), ('Rails', 'Ruby on Rails'), ('Laravel', 'Laravel'), ('Symfony', 'Symfony'), ('Codeigniter', 'CodeIgniter'), ('Aspnet', 'ASP.NET'), ('Dotnetcore', '.NET Core'), ('Phoenix', 'Phoenix'), ('Nextjs', 'Next.js'), ('Nuxtjs', 'Nuxt.js'), ('Sveltekit', 'SvelteKit'), ('Quasar', 'Quasar'), ('Vue', 'Vue.js'), ('Angular', 'Angular'), ('React', 'React'), ('Blazor', 'Blazor'), ('Flutter', 'Flutter'), ('Electron', 'Electron'), ('Qt', 'Qt'), ('Kivy', 'Kivy'), ('Tkinter', 'Tkinter'), ('Gtk', 'GTK'), ('Wxpython', 'wxPython'), ('Pyramid', 'Pyramid'), ('Bottle', 'Bottle'), ('Tornado', 'Tornado'), ('Cherrypy', 'CherryPy'), ('Falcon', 'Falcon'), ('Hanami', 'Hanami'), ('Play', 'Play Framework'), ('Struts', 'Struts'), ('Zend', 'Zend Framework'), ('Fuelphp', 'FuelPHP'), ('Cakephp', 'CakePHP'), ('Adonisjs', 'AdonisJS'), ('Feathersjs', 'FeathersJS'), ('Meteor', 'Meteor'), ('Hapi', 'Hapi.js'), ('Backbone', 'Backbone.js'), ('Ember', 'Ember.js'), ('Mithril', 'Mithril.js'), ('Marionette', 'Marionette.js'), ('Redwood', 'RedwoodJS'), ('Gatsy', 'Gatsby'), ('Remix', 'Remix'), ('Micro', 'Micro'), ('Aurelia', 'Aurelia')], help_text="Please select either 'select a framework from the list' or specify a custom entry.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='name',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('Java', 'Java'), ('C', 'C'), ('Cpp', 'C++'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('Javascript', 'JavaScript'), ('Typescript', 'TypeScript'), ('Csharp', 'C#'), ('Swift', 'Swift'), ('Kotlin', 'Kotlin'), ('Go', 'Go'), ('Rust', 'Rust'), ('Dart', 'Dart'), ('Ruby', 'Ruby'), ('Php', 'PHP'), ('R', 'R'), ('Julia', 'Julia'), ('Sql', 'SQL'), ('Plsql', 'PL/SQL'), ('Tsql', 'T-SQL'), ('Graphql', 'GraphQL'), ('Perl', 'Perl'), ('Lua', 'Lua'), ('Haskell', 'Haskell'), ('Clojure', 'Clojure'), ('Scala', 'Scala'), ('Erlang', 'Erlang'), ('Elixir', 'Elixir'), ('Fsharp', 'F#'), ('Ocaml', 'OCaml'), ('Prolog', 'Prolog'), ('Lisp', 'Lisp'), ('Scheme', 'Scheme'), ('Fortran', 'Fortran'), ('Cobol', 'COBOL'), ('Basic', 'BASIC'), ('Smalltalk', 'Smalltalk'), ('Ada', 'Ada'), ('Algol', 'ALGOL'), ('Pascal', 'Pascal'), ('Modula2', 'Modula-2'), ('Vhdl', 'VHDL'), ('Verilog', 'Verilog'), ('Jcl', 'JCL'), ('Xquery', 'XQuery'), ('Postscript', 'PostScript'), ('Bash', 'Bash'), ('Powershell', 'PowerShell'), ('Nim', 'Nim'), ('Zig', 'Zig'), ('Gams', 'GAMS'), ('Idl', 'IDL'), ('Latex', 'LaTeX'), ('Brainfuck', 'Brainfuck'), ('Whitespace', 'Whitespace'), ('Intercal', 'INTERCAL'), ('Malbolge', 'Malbolge'), ('Piet', 'Piet'), ('Befunge', 'Befunge'), ('Qsharp', 'Q#'), ('Qiskit', 'Qiskit'), ('Quipper', 'Quipper'), ('Silq', 'Silq'), ('Cirq', 'Cirq')], help_text="Please select either 'select a programming language from the list' or specify a custom entry.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tools',
            name='select_tools',
            field=models.CharField(blank=True, choices=[('Git', 'Git'), ('Github', 'GitHub'), ('Gitlab', 'GitLab'), ('Bitbucket', 'Bitbucket'), ('Docker', 'Docker'), ('Kubernetes', 'Kubernetes'), ('Jenkins', 'Jenkins'), ('Ansible', 'Ansible'), ('Puppet', 'Puppet'), ('Chef', 'Chef'), ('Terraform', 'Terraform'), ('Vagrant', 'Vagrant'), ('Npm', 'NPM'), ('Yarn', 'Yarn'), ('Pnpm', 'PNPM'), ('Webpack', 'Webpack'), ('Babel', 'Babel'), ('Esbuild', 'ESBuild'), ('Rollup', 'Rollup'), ('Parcel', 'Parcel'), ('Gulp', 'Gulp'), ('Grunt', 'Grunt'), ('Eslint', 'ESLint'), ('Prettier', 'Prettier'), ('Sonarqube', 'SonarQube'), ('Postman', 'Postman'), ('Swagger', 'Swagger'), ('Selenium', 'Selenium'), ('Cypress', 'Cypress'), ('Jest', 'Jest'), ('Mocha', 'Mocha'), ('Chai', 'Chai'), ('Junit', 'JUnit'), ('Pytest', 'PyTest'), ('Cucumber', 'Cucumber'), ('Robotframework', 'Robot Framework'), ('Newrelic', 'New Relic'), ('Datadog', 'Datadog'), ('Prometheus', 'Prometheus'), ('Grafana', 'Grafana'), ('Splunk', 'Splunk'), ('Elk', 'ELK Stack'), ('Logstash', 'Logstash'), ('Filebeat', 'Filebeat'), ('Kibana', 'Kibana'), ('Zabbix', 'Zabbix'), ('Nagios', 'Nagios'), ('Graylog', 'Graylog'), ('Honeycomb', 'Honeycomb'), ('Jaeger', 'Jaeger'), ('Opentelemetry', 'OpenTelemetry')], help_text="Please select either 'select a tool from the list' or specify a custom entry.", max_length=100, null=True),
        ),
    ]
