# Generated by Django 5.1.7 on 2025-03-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_remove_education_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(help_text='Enter your degree, e.g. Bachelor of Science, Master of Arts, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduation_date',
            field=models.DateField(help_text='Enter the date when you finished your degree'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(help_text='Enter the name of the institution where you obtained your degree', max_length=150),
        ),
    ]
