# Generated by Django 5.1.7 on 2025-05-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('brand', models.CharField(max_length=100)),
                ('device', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=100)),
                ('browser', models.CharField(max_length=100)),
            ],
        ),
    ]
