# Generated by Django 4.2 on 2025-01-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('profile_picture', models.ImageField(upload_to='branding/profile_pictures/')),
                ('background_image', models.ImageField(upload_to='branding/background_images/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='branding/resumes/')),
            ],
        ),
    ]
