# Generated by Django 4.2 on 2025-03-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalbranding',
            name='remove_bg',
            field=models.BooleanField(default=False),
        ),
    ]
