# Generated by Django 4.2 on 2025-03-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0002_personalbranding_remove_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalbranding',
            name='css_variables',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalbranding',
            name='extract_colors',
            field=models.BooleanField(default=False),
        ),
    ]
