# Generated by Django 4.2 on 2025-03-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0003_personalbranding_css_variables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalbranding',
            name='apple_touch_icon',
            field=models.ImageField(blank=True, null=True, upload_to='branding/apple_touch_icon/'),
        ),
        migrations.AddField(
            model_name='personalbranding',
            name='favicon_96x96',
            field=models.ImageField(blank=True, null=True, upload_to='branding/favicon-96x96/'),
        ),
        migrations.AddField(
            model_name='personalbranding',
            name='favicon_ico',
            field=models.ImageField(blank=True, null=True, upload_to='branding/favicon_ico/'),
        ),
        migrations.AddField(
            model_name='personalbranding',
            name='favicon_svg',
            field=models.ImageField(blank=True, null=True, upload_to='branding/favicon_svg/'),
        ),
        migrations.AddField(
            model_name='personalbranding',
            name='site_webmanifest',
            field=models.ImageField(blank=True, null=True, upload_to='branding/site_webmanifest/'),
        ),
    ]
