# Generated by Django 5.1.7 on 2025-03-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0005_remove_personalbranding_css_variables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalbranding',
            name='host_password',
            field=models.CharField(max_length=255, null=True, verbose_name='Email Host Password'),
        ),
        migrations.AddField(
            model_name='personalbranding',
            name='host_user',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email Host User'),
        ),
    ]
