# Generated by Django 5.1.7 on 2025-03-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0006_personalbranding_host_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalbranding',
            name='host_password',
        ),
        migrations.RemoveField(
            model_name='personalbranding',
            name='host_user',
        ),
    ]
