# Generated by Django 5.1.7 on 2025-03-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0007_remove_personalbranding_host_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalbranding',
            name='email_host_password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personalbranding',
            name='email_host_user',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
