# Generated by Django 5.1.7 on 2025-03-18 18:40

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0008_personalbranding_email_host_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalbranding',
            old_name='background_image',
            new_name='Dark_mode_profile_picture',
        ),
        migrations.RemoveField(
            model_name='personalbranding',
            name='email_host_password',
        ),
        migrations.RemoveField(
            model_name='personalbranding',
            name='email_host_user',
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='Primary_color',
            field=colorfield.fields.ColorField(default='none', help_text='Enter or select your primary color. This will the background color of your website.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='apple_touch_icon',
            field=models.ImageField(blank=True, help_text='Upload your Apple Touch icon in .png format. This will be used for Apple devices.', null=True, upload_to='branding/apple_touch_icon/'),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='background_color',
            field=colorfield.fields.ColorField(default='none', help_text='Enter or select your background color. This will be the background color of your website.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='bio',
            field=models.TextField(help_text='Enter your bio. This will be displayed on the about Section on the contact page.'),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='button_text_color',
            field=colorfield.fields.ColorField(default='none', help_text='Enter or select your button text color. This will be the color of the text in the buttons in your website.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='dark_Primary_color',
            field=colorfield.fields.ColorField(default='none', help_text='Enter or select your dark mode primary color. This will be the background color of your website in dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='dark_background_color',
            field=colorfield.fields.ColorField(default='none', help_text='Enter or select your dark mode background color. This will be the background color of your website in dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='dark_button_color',
            field=colorfield.fields.ColorField(default='none', help_text='Enter or select your dark mode button color. This will be the color of the buttons in your website in dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='dark_button_text_color',
            field=colorfield.fields.ColorField(default='none', help_text='Enter or select your dark mode button text color. This will be the color of the text in the buttons in your website in dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='dark_hover_color',
            field=colorfield.fields.ColorField(default='none', help_text='Enter or select your dark mode hover color. This will be the color of the buttons and the links when hovered by the cursor in your website in dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='dark_secondary_color',
            field=colorfield.fields.ColorField(default='none', help_text='Enter or select your dark mode secondary color. This will be the secondary color of your website in dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='dark_text_color',
            field=colorfield.fields.ColorField(default='none', help_text='Enter or select your dark mode text color. This will be the color of the text in your website in dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='favicon_96x96',
            field=models.ImageField(blank=True, help_text='Upload your favicon in 96x96 .png format. This will be displayed in the browser tab.', null=True, upload_to='branding/favicon-96x96/'),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='favicon_ico',
            field=models.ImageField(blank=True, help_text='Upload your favicon in .ico format. This will be displayed in the browser tab.', null=True, upload_to='branding/favicon_ico/'),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='favicon_svg',
            field=models.ImageField(blank=True, help_text='Upload your favicon in .svg format. This will be displayed in the browser tab.', null=True, upload_to='branding/favicon_svg/'),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='hover_color',
            field=colorfield.fields.ColorField(default='none', help_text='Enter or select your hover color. This will be the color of the buttons and the links when hovered by the cursor in your website.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='name',
            field=models.CharField(help_text='Enter your name', max_length=100),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='profile_picture',
            field=models.ImageField(help_text="Upload your profile picture For the lite Mode and If you want to remove the background from your profile picture, please check the 'Remove Background' checkbox.", upload_to='branding/profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload your resume in the format of .pdf or .docx', null=True, upload_to='branding/resumes/'),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='secondary_color',
            field=colorfield.fields.ColorField(default='none', help_text='Enter or select your secondary color. This will be the secondary color of your website.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='site_webmanifest',
            field=models.ImageField(blank=True, help_text='Upload your site webmanifest in .webmanifest format. This defines app metadata for browsers.', null=True, upload_to='branding/site_webmanifest/'),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='tagline',
            field=models.CharField(help_text='Enter your tagline', max_length=150),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='text_color',
            field=colorfield.fields.ColorField(default='none', help_text='Enter or select your text color. This will be the color of the text in your website.', image_field=None, max_length=25, samples=None),
        ),
    ]
