# Generated by Django 5.1.7 on 2025-03-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0009_rename_background_image_personalbranding_dark_mode_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalbranding',
            name='Dark_mode_profile_picture',
            field=models.ImageField(help_text='Upload your dark mode profile picture For the dark mode. This will be displayed in dark mode.', upload_to='branding/background_images/'),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='remove_bg',
            field=models.BooleanField(default=False, help_text='If you want to remove the background from your profile picture, please check this checkbox.'),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='resume',
            field=models.FileField(help_text='Upload your resume in the format of .pdf or .docx', null=True, upload_to='branding/resumes/'),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='tagline',
            field=models.CharField(help_text='Enter your tagline. Comma separated for multiple taglines.(eg. Frontend Developer, Backend Developer)', max_length=150),
        ),
    ]
