# Generated by Django 5.1.7 on 2025-05-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0010_alter_personalbranding_dark_mode_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalbranding',
            name='profile_picture_for_mobile',
            field=models.ImageField(help_text="Upload your profile picture For the lite Mode and If you want to remove the background from your profile picture, please check the 'Remove Background' checkbox.", null=True, upload_to='branding/profile_picture_for_mobile/'),
        ),
    ]
