# Generated by Django 5.1.7 on 2025-05-17 05:41

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0012_personalbranding_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalbranding',
            name='dark_h2_color',
            field=colorfield.fields.ColorField(default='none', help_text='Enter or select your hover color. This will be the color of the headings on the each sections in your website.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='personalbranding',
            name='h2_color',
            field=colorfield.fields.ColorField(default='none', help_text='Enter or select your hover color. This will be the color of the headings on the each sections in your website.', image_field=None, max_length=25, samples=None),
        ),
    ]
