# Generated by Django 5.1.7 on 2025-05-22 22:42

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0014_personalbranding_card_h2_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalbranding',
            name='Dark_mode_profile_picture',
            field=models.ImageField(help_text='Upload your dark mode profile picture For the dark mode. This will be displayed in dark mode.', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='branding/background_images/'),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='apple_touch_icon',
            field=models.ImageField(blank=True, help_text='Upload your Apple Touch icon in .png format. This will be used for Apple devices.', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='branding/apple_touch_icon/'),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='favicon_96x96',
            field=models.ImageField(blank=True, help_text='Upload your favicon in 96x96 .png format. This will be displayed in the browser tab.', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='branding/favicon-96x96/'),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='favicon_ico',
            field=models.ImageField(blank=True, help_text='Upload your favicon in .ico format. This will be displayed in the browser tab.', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='branding/favicon_ico/'),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='favicon_svg',
            field=models.ImageField(blank=True, help_text='Upload your favicon in .svg format. This will be displayed in the browser tab.', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='branding/favicon_svg/'),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='profile_picture',
            field=models.ImageField(help_text="Upload your profile picture For the lite Mode and If you want to remove the background from your profile picture, please check the 'Remove Background' checkbox.", storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='branding/profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='profile_picture_for_mobile',
            field=models.ImageField(help_text="Upload your profile picture For the lite Mode and If you want to remove the background from your profile picture, please check the 'Remove Background' checkbox.", null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='branding/profile_picture_for_mobile/'),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='resume',
            field=models.FileField(help_text='Upload your resume in the format of .pdf or .docx', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='branding/resumes/'),
        ),
        migrations.AlterField(
            model_name='personalbranding',
            name='site_webmanifest',
            field=models.ImageField(blank=True, help_text='Upload your site webmanifest in .webmanifest format. This defines app metadata for browsers.', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='branding/site_webmanifest/'),
        ),
    ]
