# Generated by Django 5.1.7 on 2025-05-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0016_personalbranding_og_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalbranding',
            name='short_name',
            field=models.CharField(blank=True, help_text='Enter your short name for the share cards on the social media.', max_length=100, null=True),
        ),
    ]
