# Generated by Django 5.1.7 on 2025-05-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0017_personalbranding_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalbranding',
            name='short_name',
        ),
        migrations.AddField(
            model_name='personalbranding',
            name='site_description',
            field=models.TextField(blank=True, help_text='Enter your site description. This will be used for Open Graph and Twitter Card meta tags.', null=True),
        ),
        migrations.AddField(
            model_name='personalbranding',
            name='sitetitle',
            field=models.CharField(blank=True, help_text='Enter your site title. This will be displayed in the browser tab and as the main heading of your website.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalbranding',
            name='sitetitle_on_card',
            field=models.CharField(blank=True, help_text='Enter your site title on card. This will be displayed on the card when sharing your website on social media.', max_length=100, null=True),
        ),
    ]
